### ISSUE TITLE
Incorrect result from markdown.util.etree.fromstring

### ISSUE THREAD

**Issue by traits** [cqql/pelican-katex#5]
System: Python 3.7.4  Win10
Python-Markdown: 3.2.1

https://github.com/cqql/pelican-katex/blob/def12d9254b7f5012ec84466ac84af3476ac40f8/pelican_katex/markdown.py#L41

produces nodes like `'{http://www.w3.org/1998/Math/MathML}math'`  instead `'math'`  (also for all children of `<math>`) and these strings make it into the html output . 
The result of the `render_latex` call in the preceding line seems to be correct, so something must happen in `markdown.util.etree.fromstring` (deprecated, by the way). But also when checking the underlying and now recommended `xml.etree.elementTree` the error is already visible there.

**Comment by cqql** [comment]
Thanks for finding this. I saw this when I programmed this originally but did not bother too much because I thought it was a valid - though obscure - syntax and Firefox displayed it just fine. But its source view actually highlights it in red, so something seems to be up and I fixed it in release 1.6.1. 

https://github.com/cqql/pelican-katex/blob/43f9698c58a6f8b6c633de1df2316aeb84c56be5/pelican_katex/markdown.py#L10-L22

**Comment by traits** [comment]
Thanks for the quick solution!


> Firefox displayed it just fine.

Same here - until playing with KATEX options in pelicans config, such as:

```
KATEX = {
    #"output": "mathml"
}
```

and Firefox add-ons, also [enforcing MathML rendering.](https://addons.mozilla.org/en-US/firefox/addon/native-mathml/)
